package it.polimi.ingsw.Model.CharacterCards;

public enum CharacterCardType {
    CHOOSE_ISLAND,
    COLOR_NO_INFLUENCE,
    COLOR_TO_STUDENT_BAG,
    CONTROL_ON_PROFESSOR,
    MOVE_MORE_MOTHER_NATURE,
    NO_COUNT_TOWER,
    ONE_STUDENT_TO_ISLAND,
    PUT_NO_ENTRY_TILES,
    STUDENT_TO_DINING,
    SWITCH_DINING_WAITING,
    SWITCH_STUDENTS,
    TWO_ADDITIONAL_POINTS;
}
